# Quickshell Desktop Shell -- Fudo layer
#
# Home Manager ships its own `programs.quickshell` (package, config directory,
# systemd unit). This module does NOT redeclare those; it sits on top and adds
# the parts upstream deliberately leaves to you:
#
#   1. A theme generated from Stylix. `Theme.qml` is produced from
#      `config.lib.stylix.colors` at build time, so the bar follows
#      `stylix.base16Scheme` rather than carrying its own palette (which is
#      what the Waybar config in hyprland.nix does, and why that one is stuck
#      on Catppuccin while the rest of the system is not).
#
#   2. A bar worth shipping -- the QML in ./quickshell.
#
#   3. A live-editing mode. QML wants to be edited and reloaded; the Nix store
#      is read-only. `dev.enable` points the config directory at a real
#      directory you own, seeded once from the defaults. See docs/quickshell.md.
#
# Options live under `fudo.quickshell` (matching `fudo.vr`) precisely so they
# cannot collide with the upstream module again.
#
# Only active when enabled via fudo.quickshell.enable.

{ ... }:

{ config, lib, pkgs, ... }:

with lib;
let
  cfg = config.fudo.quickshell;

  colors = config.lib.stylix.colors.withHashtag;
  inherit (config.stylix) fonts;

  # The name of the config directory under ~/.config/quickshell, passed to
  # quickshell as `--config`. A named config rather than the directory root, so
  # scratch experiments can live alongside it.
  configName = "fudo";

  # base16 role mapping. base00-07 are greyscale (background -> foreground),
  # base08-0F are the accent hues; see https://github.com/chriskempson/base16.
  themeQml = pkgs.writeText "Theme.qml" ''
    // GENERATED by Home Manager from stylix.base16Scheme -- edits are lost on
    // the next `home-manager switch`. Change colours in modules/styling.nix or
    // your user config; in dev mode, `fudo-quickshell theme` pulls a fresh copy.
    pragma Singleton

    import Quickshell

    Singleton {
        readonly property color bg: "${colors.base00}"
        readonly property color bgAlt: "${colors.base01}"
        readonly property color surface: "${colors.base02}"
        readonly property color muted: "${colors.base03}"
        readonly property color fg: "${colors.base05}"
        readonly property color accent: "${colors.base0D}"
        readonly property color ok: "${colors.base0B}"
        readonly property color warning: "${colors.base0A}"
        readonly property color critical: "${colors.base08}"

        readonly property string fontSans: "${fonts.sansSerif.name}"
        readonly property string fontMono: "${fonts.monospace.name}"

        readonly property int barHeight: ${toString cfg.barHeight}
        readonly property int gap: ${toString cfg.gap}
        readonly property int radius: ${toString cfg.radius}
    }
  '';

  # The shipped config: static QML from this repo plus the generated theme.
  defaultConfig = pkgs.runCommand "fudo-quickshell-config" { } ''
    mkdir -p $out
    cp ${./quickshell}/*.qml $out/
    cp ${themeQml} $out/Theme.qml
  '';

  qmlImportPath = concatMapStringsSep ":"
    (p: "${p}/${pkgs.qt6.qtbase.qtQmlPrefix}") cfg.extraQmlPackages;

  # nixpkgs' quickshell only carries the QML modules it was built against.
  # Anything extra (Qt5Compat.GraphicalEffects for blur/shadow being the usual
  # one) has to be put on QML2_IMPORT_PATH, and the `qs` alias needs the same
  # treatment or it quietly bypasses the wrapper.
  wrappedPackage = if cfg.extraQmlPackages == [ ] then
    pkgs.quickshell
  else
    pkgs.symlinkJoin {
      name = "quickshell-with-qml-modules";
      paths = [ pkgs.quickshell ];
      nativeBuildInputs = [ pkgs.makeWrapper ];
      postBuild = ''
        for bin in quickshell qs; do
          if [ -e "$out/bin/$bin" ]; then
            rm -f "$out/bin/$bin"
            makeWrapper ${getExe pkgs.quickshell} "$out/bin/$bin" \
              --prefix QML2_IMPORT_PATH : "${qmlImportPath}"
          fi
        done
      '';
      meta = pkgs.quickshell.meta // { mainProgram = "quickshell"; };
    };

  devTool = pkgs.writeShellApplication {
    name = "fudo-quickshell";
    runtimeInputs = [ pkgs.diffutils pkgs.systemd ];
    text = ''
      set -euo pipefail

      DEFAULTS="${defaultConfig}"
      DEV_PATH="${cfg.dev.path}"

      usage() {
        printf '%s\n' \
          'fudo-quickshell -- helpers for editing the Quickshell config live' \
          "" \
          '  init      Seed the dev directory from the Nix defaults (no overwrite)' \
          '  reset     Replace the dev directory with the Nix defaults (destructive)' \
          '  theme     Refresh only Theme.qml from the current Stylix scheme' \
          '  diff      Show how the dev directory differs from the Nix defaults' \
          '  defaults  Print the store path of the shipped config' \
          '  restart   Restart the quickshell user service' \
          '  log       Follow the quickshell journal'
      }

      case "''${1-}" in
        init)
          if [ -e "$DEV_PATH/shell.qml" ]; then
            echo "$DEV_PATH already seeded; use 'reset' to overwrite." >&2
            exit 1
          fi
          mkdir -p "$DEV_PATH"
          cp "$DEFAULTS"/*.qml "$DEV_PATH"/
          chmod -R u+w "$DEV_PATH"
          echo "Seeded $DEV_PATH"
          ;;
        reset)
          printf 'Replace everything in %s with the Nix defaults? [y/N] ' "$DEV_PATH"
          read -r reply
          case "$reply" in
            [yY]*) ;;
            *) echo "Aborted."; exit 1 ;;
          esac
          mkdir -p "$DEV_PATH"
          rm -f "$DEV_PATH"/*.qml
          cp "$DEFAULTS"/*.qml "$DEV_PATH"/
          chmod -R u+w "$DEV_PATH"
          echo "Reset $DEV_PATH"
          ;;
        theme)
          mkdir -p "$DEV_PATH"
          cp "$DEFAULTS/Theme.qml" "$DEV_PATH/Theme.qml"
          chmod u+w "$DEV_PATH/Theme.qml"
          echo "Refreshed $DEV_PATH/Theme.qml"
          ;;
        diff)
          diff -ru "$DEFAULTS" "$DEV_PATH" || true
          ;;
        defaults)
          echo "$DEFAULTS"
          ;;
        restart)
          systemctl --user restart quickshell.service
          ;;
        log)
          journalctl --user -fu quickshell.service
          ;;
        *)
          usage
          exit 1
          ;;
      esac
    '';
  };

in {
  options.fudo.quickshell = {
    enable = mkEnableOption "the Fudo Quickshell bar";

    extraQmlPackages = mkOption {
      type = types.listOf types.package;
      default = [ ];
      example = literalExpression "[ pkgs.qt6.qt5compat ]";
      description = ''
        Extra Qt packages whose QML modules should be importable from your
        config. Needed for anything nixpkgs' quickshell wasn't built against --
        most commonly qt5compat, for Qt5Compat.GraphicalEffects.
      '';
    };

    barHeight = mkOption {
      type = types.int;
      default = 32;
      description = "Height of the bar, in logical pixels.";
    };

    gap = mkOption {
      type = types.int;
      default = 10;
      description = "Spacing between bar sections and widgets.";
    };

    radius = mkOption {
      type = types.int;
      default = 6;
      description = "Corner radius used by bar widgets.";
    };

    systemdTarget = mkOption {
      type = types.str;
      default = "hyprland-session.target";
      description = ''
        systemd user target that starts the bar.

        Deliberately the Hyprland session target rather than
        graphical-session.target: on a host that offers more than one session
        (system7 offers both COSMIC and Hyprland) the broader target would
        start the bar inside the other session too, and you would get two bars
        stacked on each other.
      '';
    };

    dev = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Point the Quickshell config directory at `dev.path` (an ordinary,
          writable directory) instead of the read-only store copy, and seed it
          from the defaults on first activation. Quickshell reloads QML on
          change, so edits apply immediately with no rebuild.

          The trade-off is that the directory is then yours, not Nix's: it is
          no longer reproducible, and Theme.qml stops tracking Stylix until you
          run `fudo-quickshell theme`. Turn this off to go back to the shipped
          config.
        '';
      };

      path = mkOption {
        type = types.str;
        default = "${config.home.homeDirectory}/src/quickshell-config";
        defaultText =
          literalExpression ''"''${config.home.homeDirectory}/src/quickshell-config"'';
        description = "Directory holding the live-editable Quickshell config.";
      };
    };
  };

  config = mkIf cfg.enable {
    # Drive the upstream Home Manager module rather than reimplementing it --
    # it owns the package, the `--config` flag and the systemd unit.
    programs.quickshell = {
      enable = true;
      package = mkDefault wrappedPackage;
      activeConfig = configName;

      systemd = {
        enable = true;
        target = cfg.systemdTarget;
      };
    };

    home.packages = [ devTool ];

    # Upstream's `configs` option takes a plain path, which cannot express an
    # out-of-store symlink, so the config directory is written here instead --
    # `configs` is left empty and the two do not overlap.
    xdg.configFile."quickshell/${configName}".source = if cfg.dev.enable then
      config.lib.file.mkOutOfStoreSymlink cfg.dev.path
    else
      defaultConfig;

    # Seed once, never clobber: this is someone's working tree after the first
    # switch, and silently overwriting it would lose real work.
    home.activation.quickshellDevSeed = mkIf cfg.dev.enable
      (lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        if [ ! -e "${cfg.dev.path}/shell.qml" ]; then
          run mkdir -p "${cfg.dev.path}"
          run cp ${defaultConfig}/*.qml "${cfg.dev.path}/"
          run chmod -R u+w "${cfg.dev.path}"
        fi
      '');

    # Two bars is never what anyone wants; mkDefault so you can still force
    # Waybar back on if you want to compare them side by side.
    programs.hyprland =
      mkIf config.programs.hyprland.enable { statusBar = mkDefault "none"; };
  };
}
